### ISSUE TITLE
Download batch results is unauthorized

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#83] opened 2021-07-03 12:00 UTC
Downloading the result of a finished batch job doesn't work for me. I'm clicking the "Download" button and get shown a link, but when I click that link, I always get an unauthorized response `{"code":"AuthenticationRequired","id":"5d9721ac-ac9f-45cc-bb86-3b1545bac64c","message":"Unauthorized."}` (e.g. from [this link](https://openeo.vito.be/openeo/1.0/jobs/787d7099-6fec-4b1f-ad52-bfd83e8a3db9/results/openEO.nc), idk how useful that is here but for completeness), although I am of course still logged into the account.

**Comment by jonathom** [comment] 2021-07-04 10:49
I think this is related to [Open-EO/openeo-python-driver#50](https://github.com/Open-EO/openeo-python-driver/issues/50)

**Comment by m-mohr** [comment] 2021-07-13 11:45
Yes, that's a duplicate of https://github.com/Open-EO/openeo-python-driver/issues/50

**Closed by m-mohr** 2021-07-13 11:45 UTC
