### ISSUE TITLE
"to_scl_dilation_mask" does not work as intended with filter_spatial

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-geopyspark-driver#715] opened 2024-03-08 10:59 UTC
When executing the "to_scl_dilation_mask" process and using the `filter_spatial(geometry)`, undesired results arrive. The array contains NaN, 1.0 and very few 0.0 values.

Here is how the extracted scl dilated mask look like, other dates from the datacube yield the same result
![Image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/23267782/bd1788cb-270c-4e1a-80fb-be5ee2be0114)

The process graph is the following:
![Image](https://github.com/Open-EO/openeo-geopyspark-driver/assets/23267782/6037e510-8cae-4926-a669-391004c3a394)

I managed to reproduce the issue with this minimal example:
```
import openeo

connection = openeo.connect('http://openeo-staging.dataspace.copernicus.eu')
connection.authenticate_oidc()

cube = connection.load_collection(
    'SENTINEL2_L2A',
    bands=['B04', 'B03', 'B02', 'SCL'],
    temporal_extent=["2020-01-01", "2020-06-01"],
)

geometry = connection.load_url(
    'https://artifactory.vgt.vito.be/artifactory/auxdata-public/gfmap-temp/openeogfmap_dataframe_0.parquet',
    format="Parquet"
)

cube = cube.filter_spatial(geometry)

scl_mask = cube.process(
        "to_scl_dilation_mask",
        data=cube.filter_bands(["SCL"]),
        scl_band_name="SCL",
        kernel1_size=17,  # 17px dilation on a 20m layer
        kernel2_size=77,   # 77px dilation on a 20m layer
        mask1_values=[2, 4, 5, 6, 7],
        mask2_values=[3, 8, 9, 10, 11],
        erosion_kernel_size=3
).rename_labels("bands", ["SCL_DILATED_MASK"])

cube = cube.merge_cubes(scl_mask)
# cube = cube.linear_scale_range(0, 65534, 0, 65534)


job = cube.create_job(
    out_format='NetCDF',
    title="To_scl_dilation",
    job_options = {
        "executor-memory": "5G",
        "executor-memoryOverhead": "2G",
    }
)

job.start_and_wait()
```

**Comment by jdries** [comment] 2024-03-12 07:25
FYI, the logs do show that a pixel buffer is applied:
```
 'pixel_buffer': [38.5, 38.5]}
Loading Sentinel2 with params DataCubeParameters(256, {}, FloatingLayoutScheme, ByDay, 6, None, NearestNeighbor, 38.5, 38.5)
```
The fact that there's still an edge effect means it's either not applied properly in this case, or not large enough.

**Comment by soxofaan** [comment] 2024-03-12 13:25
FYI, as discussed in our meeting earlier this week:
- https://github.com/Open-EO/openeo-python-driver/issues/271

**Comment by jdries** [comment] 2024-03-18 12:11
Reassigned in Emile's absence, will look for unit test.

**Comment by jdries** [comment] 2024-03-18 13:47
@GriffinBabe  I've been trying to reproduce this. I'm focusing on the case where there are multiple patches, and using sample_by_feature.
In that case, there does not seem to be a border effect, both with and without merging optical bands.
I've used your geoparquet with 3 samples, focusing on date range: ("2020-03-29","2020-04-06")

Can you also try again, to help figure out what part leads to these artifacts?

**Comment by GriffinBabe** [comment] 2024-03-18 14:43
@jdries 
Indeed, when applying `sample_by_feature` it works (I didn't applied it previously as I was told by Stefaan to not take this  into account for the moment)

There is still the issue with the border though. You said previously that I'm applying a pixel buffer of a certain size:
> FYI, the logs do show that a pixel buffer is applied:
> 
> ```
>  'pixel_buffer': [38.5, 38.5]}
> Loading Sentinel2 with params DataCubeParameters(256, {}, FloatingLayoutScheme, ByDay, 6, None, NearestNeighbor, 38.5, 38.5)
> ```
> 
> The fact that there's still an edge effect means it's either not applied properly in this case, or not large enough.

Is this related to the size of the polygons? I suppose this is, because that's the only moment in the pipeline where I am choosing a buffer, but the polygon size is 64x64 pixels, so it should be 32.0, not 38.5

**Comment by jdries** [comment] 2024-03-18 15:17
@GriffinBabe can you share the code again that produces this? Because I don't get the border.

The buffer is calculated based on the largest kernel size, so that the convolution is applied correctly. This is what normally should prevent border effects. The value of 38.5 is correct for a kernel size of 77.

**Comment by GriffinBabe** [comment] 2024-03-18 15:27
This is the code:

```
import openeo

connection = openeo.connect('http://openeo-staging.dataspace.copernicus.eu')
connection.authenticate_oidc()

cube = connection.load_collection(
    'SENTINEL2_L2A',
    bands=['B04', 'B03', 'B02', 'SCL'],
    temporal_extent=["2020-01-01", "2020-06-01"],
)

geometry = connection.load_url(
    'https://artifactory.vgt.vito.be/artifactory/auxdata-public/gfmap-temp/openeogfmap_dataframe_threelocs.parquet',
    format="Parquet"
)

cube = cube.filter_spatial(geometry)

scl_mask = cube.process(
        "to_scl_dilation_mask",
        data=cube.filter_bands(["SCL"]),
        scl_band_name="SCL",
        kernel1_size=17,  # 17px dilation on a 20m layer
        kernel2_size=77,   # 77px dilation on a 20m layer
        mask1_values=[2, 4, 5, 6, 7],
        mask2_values=[3, 8, 9, 10, 11],
        erosion_kernel_size=3
).rename_labels("bands", ["SCL_DILATED_MASK"])

cube = cube.merge_cubes(scl_mask)
# cube = scl_mask
# cube = cube.linear_scale_range(0, 65534, 0, 65534)


job = cube.create_job(
    out_format='NetCDF',
    title="To_scl_dilation",
    job_options = {
        "executor-memory": "5G",
        "executor-memoryOverhead": "2G",
    },
    sample_by_feature=True,
)

job.start_and_wait()
```

**Comment by jdries** [comment] 2024-03-18 16:20
Thanks, now I spotted it: you do the filter_spatial before to_mask_scl_dilation. Problem is that this process actually needs neighbouring pixels, but filter_spatial will remove them, so output is no longer correct.
Solution is to simply move filter_spatial after mask dilation process, that seems to work for me.

**Closed by jdries** 2024-03-18 16:20 UTC
