### ISSUE TITLE
apply_dimension without target_dimension fails

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#108] opened 2021-09-13 13:39 UTC
Spin-off from #106 :
using `apply_dimension(dimension="t"` without a `target_dimension` fails with unhelpful error message

e.g.
```python
from openeo import connect
con = connect("openeo-dev.vito.be")
con.authenticate_oidc(provider_id="egi")

cube = con.load_collection(
        collection_id="LANDSAT8_L2",
        spatial_extent={"west": 3.7, "east": 3.75, "south": 51.03, "north": 51.05},
        temporal_extent=["2021-04-25", "2021-05-28"],
        bands=["B06", "B05", "B03"]
    )

cube = cube.apply_dimension(
    dimension="t", 
#     target_dimension="bands", 
    process=lambda data: quantiles(data, probabilities=[0.2])
)

cube.download("tmp.nc", format="NetCDF")
```
-> 
```OpenEoApiError: [500] unknown: geotrellis.layer.SpatialKey cannot be cast to geotrellis.layer.SpaceTimeKey```

the solution is setting `target_dimension="bands", ` but that is not obvious from this error message

**Comment by soxofaan** [comment] 2021-09-13 13:45
also: setting `target_dimension="foo", `  still causes
```
OpenEoApiError: [500] unknown: geotrellis.layer.SpatialKey cannot be cast to geotrellis.layer.SpaceTimeKey
```

**Comment by jdries** [comment] 2021-09-14 05:49
Stack trace below. The problem is probably a 'groupBy' operation, to group data on the time dimension, that tries to preserve the spacetime partitioner, which doesn't work when actually trying to use it.
Already occured here:
https://github.com/Open-EO/openeo-geotrellis-extensions/commit/500e978848f31a015b201a3cac260cdbe649e007
So will need to figure out in which code path(s) there's still an issue.
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 28.0 failed 4 times, most recent failure: Lost task 5.3 in stage 28.0 (TID 972, epod079.vgt.vito.be, executor 178): java.lang.ClassCastException: geotrellis.layer.SpatialKey cannot be cast to geotrellis.layer.SpaceTimeKey
	at org.openeo.geotrelliscommon.package$SpaceTimeByMonthPartitioner$.toIndex(package.scala:40)
	at geotrellis.spark.partition.SpacePartitioner.getPartition(SpacePartitioner.scala:45)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jdries** [comment] 2021-09-14 06:06
made a first commit that may fix the issue, but may require some more investigation as well
For me, this probably worked because I enabled a different partitioner with a feature flag, both cases need to be covered in the tests.

**Comment by jdries** [comment] 2021-09-21 06:37
I was now also able to reproduce this in a unit test, closing!

**Closed by jdries** 2021-09-21 06:37 UTC
