### ISSUE TITLE
fit_class_random_forest throws an error on CDSE backend

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#582] opened 2023-11-10 12:49 UTC
It looks like fit_class_random_forest is not properly supported on the CDSE backend:
```
OpenEO batch job failed: ReadError('/batch_jobs/ml_models/model-231030c581db4d559892ae33a06db0c6/randomforest.model.tar.gz is not a compressed or uncompressed tar file)
```

**Comment by jdries** [comment] 2024-02-29 07:07
closing as duplicate of: https://github.com/Open-EO/openeo-geopyspark-driver/issues/562

**Closed by jdries** 2024-02-29 07:07 UTC
