### ISSUE TITLE
add retry for https://stac.openeo.vito.be access

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#973] opened 2024-12-16 13:15 UTC
```
 File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 2347, in load_stac
    return env.backend_implementation.load_stac(url=url, load_params=load_params, env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 755, in load_stac
    return load_stac.load_stac(url, load_params, env, layer_properties={}, batch_jobs=self.batch_jobs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/load_stac.py", line 196, in load_stac
    stac_object = _await_stac_object(url, poll_interval_seconds, max_poll_delay_seconds, max_poll_time)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/load_stac.py", line 641, in _await_stac_object
    stac_object = pystac.read_file(href=url)  # TODO: add retries and set timeout
  File "/opt/openeo/lib/python3.8/site-packages/pystac/__init__.py", line 161, in read_file
    return stac_io.read_stac_object(href)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 234, in read_stac_object
    d = self.read_json(source, *args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 205, in read_json
    txt = self.read_text(source, *args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 282, in read_text
    return self.read_text_from_href(href)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 300, in read_text_from_href
    with urlopen(req) as f:
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib64/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by JeroenVerstraelen** [comment] 2024-12-16 13:16
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/load_stac.py#L645

**Comment by bossie** [comment] 2024-12-16 13:25
Duplicate of #818.

**Closed by bossie** 2024-12-16 13:25 UTC
