### ISSUE TITLE
Job title is not stored

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-geopyspark-driver#124] opened 2022-02-01 08:51 UTC
When creating a batch job, the job title is not stored and it is therefore difficult understanding what was it about without reading the process graph.
Same issue connecting directly to VITO and through the Platform aggregator.

![image](https://user-images.githubusercontent.com/31700619/151938158-ffceb809-4021-4c14-bce1-0bc06bb0f9c6.png)
![image](https://user-images.githubusercontent.com/31700619/151938221-3a479655-3e75-4d91-a463-979dae20dbc6.png)

**Comment by jdries** [comment] 2022-02-01 09:06
Weird, the behavior I see is that the title pops up when I click the 'i' button. So the title is stored, I also used this a lot.
Question now is if this is a regression in the web editor or the backend?

**Comment by clausmichele** [comment] 2022-02-01 09:10
> Weird, the behavior I see is that the title pops up when I click the 'i' button. So the title is stored, I also used this a lot. Question now is if this is a regression in the web editor or the backend?

I've also just noticed that!

**Comment by jdries** [comment] 2022-02-01 10:11
The backend indeed no longer includes the title when the full job listing is requested.
@bossie  is this something we changed recently?

**Comment by bossie** [comment] 2022-02-02 10:20
We did change that recently. The source of the confusion was the fact that the "title" property in the job listing response is optional/not marked **required** : https://openeo.org/documentation/1.0/developers/api/reference.html#operation/list-jobs so we decided to omit it.

Turns out it means that the user is not required to specify a title, rather than: this property can be omitted from the response.

We'll do as the spec recommends and "[omit] all optional non-scalar values from objects in jobs."

**Comment by m-mohr** [comment] 2022-02-04 09:52
> We'll do as the spec recommends and "[omit] all optional non-scalar values from objects in jobs."

title is a scalar and as such should be included. Could be that we understand scalar differently and I should clarify in the spec. That was meant to include null, boolean, strings, numbers and not include arrays and objects. See https://en.wikipedia.org/wiki/Scalar_processor#Scalar_data_type

**Comment by m-mohr** [comment] 2022-02-04 10:10
Clarified: https://github.com/Open-EO/openeo-api/commit/a886c8f2e190ccd39e5eb14b79a10d75c95426d7

**Comment by jdries** [comment] 2022-02-25 10:23
Should be fixed, at least on openeo-dev!

**Closed by jdries** 2022-02-25 10:23 UTC
