### ISSUE TITLE
load_stac: support loading unfinished results

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#489] opened 2023-08-10 06:13 UTC
Using load_stac, we can normally also load openEO generated results provided by a signed url. 
Using the 'partial' query parameter, it seems possible to get a canonical link to a job that is still running:
https://api.openeo.org/#tag/Data-Processing/operation/list-results
(support for 'partial' needs to be added to our backend)

So if our backend receives a process graph with a load_stac, it should only start the actual processing when all dependencies are finished!
This is an important piece of the puzzle for federated processing, because it allows the aggregator to perform job splitting without keeping track of the various jobs itself: it can just schedule all jobs and forward them to the respective backends. Hence it also no longer needs a long lived token.

**Comment by bossie** [comment] 2023-08-10 12:02
As discussed: works similarly to SHub batch process polling.

**Comment by bossie** [comment] 2023-08-17 14:41
"openeo:status" is in the root of the STAC Collection object.

Some considerations/decisions that make sense at this time but might need revisiting:

- since these dependencies are batch jobs and, by definition, can take a bit of time, this flow only makes sense in the context of a batch job (~ SHub batch processes)
- what about a `load_stac(canonical_partial_job_results)` in a `/result` context? Never wait but continue with (partial) results or abort?
- re: the initial check, if "openeo:status" is missing or == "finished", just proceed; if "error" or "canceled" continue with partial results or abort?
- re: the polling check, if "openeo:status" is missing, just proceed; if "error" or "canceled" continue with partial results or abort?

**Comment by bossie** [comment] 2023-08-25 11:12
Currently implemented as such:

- `load_stac` of partial job results that have already finished with "openeo:status": "error" or "openeo:status": "canceled": just proceed with the batch job; this allows the user to load partial results (their responsibility).
- `load_stac` of unfinished partial job results that eventually fail with "error" or "canceled": fail the the batch job; otherwise the job would proceed with partial results and the user would never know (unless they check the logs)
- `load_stac` of partial job results in `/result`: never wait, proceed with partial results (same reasoning, their responsibility).

**Comment by bossie** [comment] 2023-08-29 13:44
Did some testing and loading partial job results from OpenEO dev takes a very long time (but not always):

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openeo-dev.vito.be', port=443): Max retries exceeded with url: /openeo/jobs/j-0977e9aed9da431f872b716c20e500cf/results/...?expires=1693901122&partial=true (Caused by ReadTimeoutError("HTTPSConnectionPool(host='openeo-dev.vito.be', port=443): Read timed out. (read timeout=60)"))
```

**Comment by bossie** [comment] 2023-09-01 05:58
A `load_stac` on Terrascope from an unfinished job on CDSE works after the latest fixes. :partying_face:

**Comment by bossie** [comment] 2023-09-01 07:18
With both jobs on Terrascope, it still hangs.

TimingLogger when starting the `load_stac` batch job (`backend.py`):
> load_stac(https://openeo-dev.vito.be/openeo/1.1/jobs/j-dcc5727733a34956a34ca97a16ef57ef/results/...&partial=true): extract "openeo:status": start 2023-09-01 06:38:21.490097

TimingLogger in the corresponding get partial job results call (views.py):
> backend_implementation.batch_jobs.get_job_info(job_id='j-dcc5727733a34956a34ca97a16ef57ef', user_id='7d523381374b62e6f2aad1f2f9fb6eddf624d382a8f71db6dcf5788e3aae0af3@egi.eu'): start 2023-09-01 06:39:14.346796

In both cases, there's no corresponding "end/elapsed" log.

Added some more logging to the implementation of `get_job_info`.

**Comment by bossie** [comment] 2023-09-01 07:49
I think the mutex introduced in 656b7ceb2a658834ea374cdab1ac182bb2126843 leads to a deadlock.

`GeoPySparkBackendImplementation` is a singleton, therefore `GpsBatchJobs` is a singleton, therefore `DoubleJobRegistry` is a singleton, and the mutex prevents it from being used as a context manager in multiple threads at the same time.

The mutex is acquired for the whole of `start_job`, which includes an HTTP call to get the batch job details and that will also try to acquire the same mutex.

**Comment by bossie** [comment] 2023-09-04 07:28
Confirmed and subsequently fixed by splitting up the `DoubleJobRegistry` context manager blocks in `_start_job()`.

Why was this `RLock` introduced @soxofaan ?

**Comment by bossie** [comment] 2023-09-05 09:11
Both original + `load_stac` jobs on Terrascope works as well.

**Closed by bossie** 2023-09-05 09:11 UTC
