### ISSUE TITLE
Ingest jobs and job results into ES

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#236] opened 2022-10-08 11:56 UTC
Set up synchronization of jobs and job results with ES.
This allows us to build dashboards that give more insight into job specific metrics.

**Comment by soxofaan** [comment] 2022-10-19 14:01
Closed duplicate #246  I just created

> Reference story for moving from Zookeeper to Elastic Search for batch job metadata.
> Zookeeper was fine as initial POC, but scalability and flexibility (e.g. build an admin UI on top of it) is becoming a problem.
We decided to migrate to an Eleastic Search based solution

also related:
- #245

**Comment by soxofaan** [comment] 2022-10-20 09:51
internal ticket/ref: FD-5452

**Comment by soxofaan** [comment] 2022-12-06 14:09
closing as duplicate of https://github.com/Open-EO/openeo-python-driver/issues/153

**Comment by soxofaan** [comment] 2023-01-11 10:43
Change of plan.
Current approach is to refactor the current `JobTracker` implementation in `job_tracker.py`, but it turns out that it's hard to verify that things keep working on real resources (yarn, k8s, zk, ES, ...), because deploying/running the new version (in a feature branch) in these different contexts is not trivial.  Merging the related PR would also mean a hard switch to the new implementation for all targets (YARN deploy and K8s deploy), with no clean way to roll back (PR currently involved a lot of merge conflicts). This is risky if the new implementation is poorly verified.
 
New plan is to keep original `job_tracker.py` untouched, and just add a new implementation in, say, `job_tracker_v2.py`. Because of how the job trackers work it should be fine to run the original jobtracker concurrently with the v2 version. This gives more room to properly finetune the new implementation

**Comment by bossie** [comment] 2023-02-14 07:10
There's [no SparkContext in an async_task](https://kibana-infra.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-12T23:00:00.000Z',to:'2023-02-13T23:00:00.000Z'))&_a=(columns:!(message,levelname,filename),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',key:job_id,negate:!f,params:(query:j-c7a843be5cdf4004af5b927199f72daf),type:phrase),query:(match:(job_id:(query:j-c7a843be5cdf4004af5b927199f72daf,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',key:levelname,negate:!f,params:(query:ERROR),type:phrase),query:(match:(levelname:(query:ERROR,type:phrase))))),index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))); it does have a dedicated JavaGateway instance that you'll want to use.

**Comment by soxofaan** [comment] 2023-02-14 08:44
@bossie thanks for reporting this, I hope it is fixed by  b4b65f5

**Comment by soxofaan** [comment] 2023-05-09 07:41
with https://github.com/Open-EO/openeo-job-registry-elastic-api/issues/28 being fixed, we can now proceed with improving the scope of EJR (elastic job registry) and DoubleJobRegistry.

for example: switching priority between ZK based registry and EJR registry for some operations

**Comment by soxofaan** [comment] 2023-08-30 07:47
Currently working on making the ZK side of DoubleJobRegistry optional

**Comment by soxofaan** [comment] 2023-09-12 13:27
closing this long standing issue, follow up is for #498

**Closed by soxofaan** 2023-09-12 13:27 UTC
Labels: architecture
