### ISSUE TITLE
job options on CDSE results in Invalid maximum heap size: -Xmx1gb

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#461] opened 2023-06-22 13:01 UTC
When using job options on CDSE such as:
```
job = datacube.create_job(out_format=output_format, title=title, description='benchmarking-creo', job_options={
    'driver-memory': '1gb',
    'driver-memoryOverhead': '500mb'
})
```
Then it can happen that the user receives this error message:
```
openeo.rest.JobFailedException: Batch job 'j-27a3eccb850e4cc499c746c1ec7b7b89' didn't finish successfully. Status: error (after 0:00:50).
```
There will be no error logs in Elastic but the job registry will list the batch job with status ERROR. You can only find out what went wrong by using:
```
kubectl logs job-c7100a2ddf-e3e8dcf3-ac7c-46c3-8-driver -n spark-jobs-staging
```
Which shows this error:
```
+ exec /usr/bin/tini -s -- /usr/local/spark/bin/spark-submit --conf spark.driver.bindAddress=... --conf spark.executor.extraClassPath=/opt/openeo-logging-static.jar --conf spark.driver.extraClassPath=/opt/openeo-logging-static.jar --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner local:///opt/openeo/lib64/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py /batch_jobs/j-c7100a2ddf8140ae8a739aeacd01af54/job_specification.json /batch_jobs/j-c7100a2ddf8140ae8a739aeacd01af54 out stdout job_metadata.json 1.1.0 '[]' ... 0.0
Invalid maximum heap size: -Xmx1gb
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I believe it's best we communicate this error better to the user. Or communicate that job options are not fully supported on CDSE. Perhaps if the logs show something like this:
```
job j-c7100a2ddf8140ae8a739aeacd01af54: status change from created to error
```
Then we can tell the user that something went wrong during the startup of the batch job and that they might have to check the job options.

**Comment by bossie** [comment] 2023-06-27 06:53
Those job options are supported, it's just that they have different units. These work:

```python
{'driver-memory': '1g', 'driver-memoryOverhead': '500m'}
```

Otherwise it's a duplicate of #401.

**Closed by bossie** 2023-06-27 06:53 UTC
