### ISSUE TITLE
Make Item ID configurable in Open-EO output STAC metadata

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-geopyspark-driver#721] opened 2024-03-13 13:07 UTC
@jdries In order to re-merge output samples with the correct input data we would require to have the item id in the output STAC metadata configurable by the user

**Comment by soxofaan** [comment] 2024-03-13 14:58
is this by any chance a duplicate of https://github.com/Open-EO/openeo-geopyspark-driver/issues/722 ?

**Comment by kvantricht** [comment] 2024-03-28 08:22
> is this by any chance a duplicate of [#722](https://github.com/Open-EO/openeo-geopyspark-driver/issues/722) ?

@GriffinBabe could you check this and either assign this ticket to someone who could take up the task or close it when it's already done?

**Comment by VincentVerelst** [comment] 2024-03-28 13:25
https://github.com/Open-EO/openeo-geopyspark-driver/issues/722 should have indeed closed this issue as well (duplicate).

**Closed** 2024-04-17 09:29 UTC
