### ISSUE TITLE
Remove custom CGLS & Agera5 Pyramidfactory classes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#219] opened 2022-09-14 06:39 UTC
CGLS and Agera5 now both have a custom PyramidFactory that extends the generic Sentinel2PyramidFactory:

org.openeo.geotrellis.file.AgEra5PyramidFactory2
org.openeo.geotrellis.file.CglsPyramidFactory2

These custom implementations only override the opensearchclient. So we basically have a case where we only require 'composition' (as a pattern), but now combine composition and inheritance.

These datasets might also be written in terms of disk based collections:
org.openeo.geotrellis.geotiff.PyramidFactory#from_disk
These disk collections also have better test coverage, but do not yet extend Sentinel2PyramidFactory, so also an opportunity there.

Need to perform a small refactor so that the custom opensearchclient class can be created either from Python directly or through a new factory class in scala. Note that we also have some code duplication at the level of Agera5SearchClient and GlobalNetCDFSearchClient.

The goal of this issue is to reduce maintenance and increase test coverage, by reducing the amount of branches and dataset specific code in openeogeotrellis.layercatalog.GeoPySparkLayerCatalog.load_collection

Existing test coverage for agera5:
tests.test_load_collection.test_load_collection_data_cube_params

**Comment by JeroenVerstraelen** [comment] 2022-10-20 10:15
@jdries I have a few questions regarding this issue.

First, to only use composition on the Sentinel2PyramidFactory class we could remove the "createOpenSearch()" method and use an opensearchclient as a parameter in the constructor instead. Where we leave the responsibility to create opensearchclient to the geopysparkdriver. That way file-cgls2, file-agera5, and file-oscars in layercatalog.py will all create the same Sentinel2PyramidFactory class. But in this case, they still need separate branches to create their own opensearchclient. 

Another option would be to edit the OpensearchClient.
These are the required parameters to create each OpensearchClient:
- Oscars:
  * openSearchEndpoint: String
- Cgls
  * dataGlob: String, 
  * dateRegex: String, 
  * netcdfVariables: util.List[String]
- AgEra5PyramidFactory2
  * dataGlob: String, 
  * dateRegex: String,
  * bandFileMarkers: util.List[String]

I could edit the constructor of the opensearchclient so that it distinguishes an url from a dataglob and add the dateRegex and variables as optional parameters. That way the level of branching in layercatalog.py is reduced as file-cgls2, file-agera5, and file-oscars can all use the same path. It makes sense to put all that logic in the openeo-opensearch-client project, all other projects then just see a OpenSearchClient with a getProducts method.

**Comment by jdries** [comment] 2022-10-20 10:45
Question is, where do we want the branching? Maybe having that in python is easier, because it allows for faster updates compared to the scala code?

**Comment by JeroenVerstraelen** [comment] 2022-10-20 14:35
Note: The decided on tactic is to add a factory class that creates the OpenSearchClient and the Factory for all three types: oscars, cgls, and agera5.

**Comment by JeroenVerstraelen** [comment] 2023-01-26 07:04
Can we also remove the Sentinel2RadiometryPyramidFactory? It does not appear to be used in the Python code, and in the scala code it is only used in Sentinel2RadiometyBenchmark.scala and Sentinel2RadiometryPyramidFactoryTest.scala. This would also allow us to remove AbstractPyramidFactory since it is only being used by the Sentinel2RadiometryPyramidFactory.  

That would leave us with:
- org.openeo.geotrellis.file.PyramidFactory For file-s1-coherence, file-s2, file-cgls, file-cgls2, file-agera5, file-oscars
- ProbaVPyramidFactory For file-probav
- CglsPyramidFactory For legacy file-cgls
- FileRDDFactory Only used in s1backscatter (FileRDDFactory#creo)
- org.openeo.geotrellis.geotiff.PyramidFactory Used for sentinel-hub and geotiff layer types, and in load_result + load_disk_data.

For the removal of CglsPyramidFactory, we have CglsPyramidFactoryTest#compare_factory1_to_factory2 apparently when using datacube_seq (for single_level) the legacy version uses a ZoomedLayoutScheme while the new version uses a FloatingLayoutScheme. I believe the new version is the intended behaviour for both datacube_seq and pyramid_seq. Does that mean that we can remove the legacy CglsPyramidFactory or is there a reason to keep it?

The geotiff.PyramidFactory has a lot of overlap now with file.PyramidFactory with a dataGlob based OpenSearchClient. Is it the intention that these two are merged in the future?

The FileRDDFactory currently looks like just an abstraction of the Creodias OpenSearchClient but it does have its own implementation of readMultibandTileLayer that we will have to test if it can be merged. Should this class also be merged into file.PyramidFactory eventually?

**Comment by jdries** [comment] 2023-01-26 12:59
- We can remove legacy CglsPyramidFactory. For pyramid_seq, I believe a zoomed layout scheme is correct default
- use of geotiff.PyramidFactory will also be phased out indeed
- FileRDDFactory is something separate, maybe keep it as is for now

**Closed** 2023-02-02 09:30 UTC
