### ISSUE TITLE
Unexpected results when using a FeatureCollection of Polygons as geometry input for `aggregate_spatial`

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-geopyspark-driver#622] opened 2023-12-18 15:27 UTC
https://openeo.vito.be/openeo/1.2/jobs/j-2312187d0f864fa2a6c72f3dbc5a42b4/results/MDhlMmE0MDA2MTE1NTU4OWJhNDBjZDAyY2JjMzNiZmFlNWUyMGFjOWRhMDAxNjRiNzgzY2M2OTc2MjdjMzQ0YUBlZ2kuZXU%3D/edba0d56f4d2bd80f75277f1da4f5286?expires=1703505654

In the above process graph, a FeatureCollection consisting of 25 Polygons is given as the input for the geometry in `aggregate_spatial`. The resulting csv consists of just one row, instead of the expected 25 rows. It is unclear over which geometry the results are aggregated. 

When the 'bbox' keys are removed from the FeatureCollection the resulting CSV does give the expected result of 25 rows.

**Comment by soxofaan** [comment] 2024-01-09 15:37
FYI: that link has expired by now, can you share that process graph differently (dump it inline if not too large, otherwise as attachment, or with https://gist.github.com/ or something else ...)

**Comment by soxofaan** [comment] 2024-01-12 15:03
I noticed that the feature collection has very small polygons (circles of 1m radius I guess). Could you try to reproduce this issue with two or three larger polygons instead?

**Comment by VincentVerelst** [comment] 2024-01-15 14:21
Using a featurecollection of circle polygons with radius 10km, I cannot reproduce the issue. I.e. I have entered three polygons as an input, and receive three rows of data as an output. See for example:
[
j-24011535425948519b9566211507d61c_10km_radius.json](https://github.com/Open-EO/openeo-geopyspark-driver/files/13939807/j-24011535425948519b9566211507d61c_10km_radius.json)

When setting the radius back to 1m, I'm still able to reproduce it. See for example
[
j-2401156c36c94a9c8967d8428eed5234_1m_radius.json](https://github.com/Open-EO/openeo-geopyspark-driver/files/13939826/j-2401156c36c94a9c8967d8428eed5234_1m_radius.json)

**Comment by soxofaan** [comment] 2024-01-16 09:53
Can you indicate whether this a blocker for an important project (e.g. WorldCereal), to help prioritizing this ticket

**Comment by VincentVerelst** [comment] 2024-01-16 10:00
I think not, since WorldCereal needs patch extractions of 640x640m, for which this issue is not relevant.

**Comment by jdries** [comment] 2024-01-25 12:41
Note that the csv should contain a column with the index of the polygon.
No rows means that there was no data for that polygon.

A polygon with a radius of 1m doesn't work well with 10m resolution data, because the pixel center has to intersect. In that case, it is actually better to use points instead of small polygons.

Closing as this is expected behaviour.

**Closed by jdries** 2024-01-25 12:41 UTC
Labels: bug

**Comment by soxofaan** [comment] 2024-01-25 14:45
> No rows means that there was no data for that polygon.

should there be an empty row for polygons without data, otherwise the association between rows and polygon index is lost?

**Comment by jdries** [comment] 2024-01-25 18:59
As far as I know, our CSV file have a feature index column to map to the original polygon, so users should never rely on row order for this. (That's only the case in our custom json format.)
________________________________
