### ISSUE TITLE
`list_jobs()` returns (old) finished jobs that probably were deleted in the past.

### ISSUE THREAD

**Issue by theroggy** [Open-EO/openeo-geopyspark-driver#523] opened 2023-09-28 11:24 UTC
`list_jobs()` returns a bunch of old jobs that were probably deleted at the time, but now pop up again as "finished" jobs again, but cannot be deleted.

An example:
```
13:17:28.193|INFO|cropclassification.util.openeo_util|job {'created': '2023-05-04T15:16:20Z', 'id': 'j-ce40e39f402c497f952c4827aa5386c6', 'status': 'finished', 'updated': '2023-05-04T15:18:26Z'} doesn't have a title, so just delete it
13:17:28.296|WARNING|cropclassification.util.openeo_util|[404] JobNotFound: The batch job 'j-ce40e39f402c497f952c4827aa5386c6' does not exist. (ref: r-745b28ae9c5f4584bc32a9cafbdd5516)
```

**Comment by soxofaan** [comment] 2023-09-29 09:36
(I guess this will be from  a openeo-geopyspark-driver powered openeo backend, so moved to openeo-geopyspark-driver project)

**Comment by soxofaan** [comment] 2023-09-29 09:48
Do you have an idea when this happened?
I see the job was finished on 2023-05-04T15:18:26Z.
When did you do the listing of jobs, and when did you try the delete?
Your logs only show time `13:17:28.296`, but an (approx) date would help figuring out what is going on here

**Comment by theroggy** [comment] 2023-09-29 11:31
> Do you have an idea when this happened? I see the job was finished on 2023-05-04T15:18:26Z. When did you do the listing of jobs, and when did you try the delete? Your logs only show time `13:17:28.296`, but an (approx) date would help figuring out what is going on here

I'm sorry. The logging is from yesterday, Brussels time ;-).

**Comment by soxofaan** [comment] 2023-09-29 11:55
So you can still reproduce listing this `j-ce40e39f402c497f952c4827aa5386c6` job when doing `connection.list_jobs()`?

What happens when you do `connection.job("j-ce40e39f402c497f952c4827aa5386c6")` ? an error, or you get a `BatchJob` instance?

**Comment by theroggy** [comment] 2023-09-29 12:20
> connection.job("j-ce40e39f402c497f952c4827aa5386c6")

A `BatchJob`.

**Comment by soxofaan** [comment] 2023-09-29 14:01
OK I think I found the problem, at the moment we are in the process of migrating from one job metadata storage solution (which only holds last X months window of jobs) to another (with no cutoff).
The `list_jobs()` includes data from the newer system, 
while individual  job inspection, like `connection.job("...")`  first looks in the old storage, which fails immediately and the newer system isn't being used (yet) as fallback.

**Comment by soxofaan** [comment] 2023-09-29 14:04
> ... old jobs that were probably deleted at the time ...

are you sure you deleted them explicitly, or you just got used to not seeing them listed (until recently)?

**Comment by theroggy** [comment] 2023-09-29 14:55
> > ... old jobs that were probably deleted at the time ...
> 
> are you sure you deleted them explicitly, or you just got used to not seeing them listed (until recently)?

I'm pretty sure... in my code there are two options when it is started, depending on a switch:
- either all existing jobs are deleted.
- or the exisitng jobs are looped and for each the result is downloaded + the job is deleted.

It is noteworthy that the jobs don't seem to have a `title`... and my code crashed on this because it was expected for them to have one... So either the "title" was lost somehow, or they never had and weren't returned by `list_jobs` in the past so they were invisible to my code?

**Comment by soxofaan** [comment] 2023-09-29 15:10
ok noted, so the job deletion feature is important for your current workflow? 

I would however recommend to not depend too much on it at the moment, because it is currently partially broken I'm afraid (related to https://github.com/Open-EO/openeo-python-driver/issues/163) 
Instead, as workaround for the moment, I would consider using different means to identify which jobs have to be downloaded (e.g. use job_id in download folder name so you see it is already downloaded

> It is noteworthy that the jobs don't seem to have a title..

Per [openEO spec](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/describe-job) the job title is an optional field, so you can not depend on the assumption it is always available.

**Comment by theroggy** [comment] 2023-09-29 16:01
> ok noted, so the job deletion feature is important for your current workflow?

Yes, but if needed I can easily make a change for it to stop being blocking...

Rough workflow: 
In a loop for e.g. different time periods or bands or...:
- format a Filename based in the parameters defining the data to be produced on openeo
- if such a file exists already return
- else check if there is an openeo job with that filename as a title, and if this is the case, download result and return
- else create a job with the filename as title and return

After this, poll while there are still jobs and for finished jobs, download results + delete job
I can put a check here to ignore jobs where the output file already exists to cope with the delete not working...

> I would however recommend to not depend too much on it at the moment, because it is currently partially broken I'm afraid (related to [Open-EO/openeo-python-driver#163](https://github.com/Open-EO/openeo-python-driver/issues/163)) Instead, as workaround for the moment, I would consider using different means to identify which jobs have to be downloaded (e.g. use job_id in download folder name so you see it is already downloaded
> 
> > It is noteworthy that the jobs don't seem to have a title..
> 
> Per [openEO spec](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/describe-job) the job title is an optional field, so you can not depend on the assumption it is always available.

No, I know it is not a mandatory field, but in my workflowd they always have one. Nonetheless it is obviously better not to have crashing code when the title isn't filled out...

**Comment by soxofaan** [comment] 2023-10-10 08:29
FYI: we fixed the batch job deletion issue (https://github.com/Open-EO/openeo-python-driver/issues/163), which should make sure that batch jobs can be fully deleted and don's show up again in `list_jobs()`. This will become available on openeo.vito.be with the next production release (this week or next week I guess).

**Comment by soxofaan** [comment] 2023-10-26 16:41
FYI The fix for batch job deletion is available on openeo.vito.be since yesterday.
I'm going to close this ticket for now, but feel free to reopen if you still encounter issues.

**Closed by soxofaan** 2023-10-26 16:41 UTC
